"""添加route_permissions表

Revision ID: 0a23b8e15b43
Revises: 7a88cb9e988a
Create Date: 2025-06-16 14:46:01.790202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0a23b8e15b43'
down_revision: Union[str, None] = '7a88cb9e988a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_permissions_id'), 'route_permissions', ['id'], unique=False)
    op.create_table('role_permission',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], )
    )
    op.drop_index('ix_announcements_id', table_name='announcements')
    op.drop_table('announcements')
    op.alter_column('departments', 'description',
               existing_type=mysql.VARCHAR(length=500),
               type_=sa.String(length=100),
               nullable=True)
    op.drop_table_comment(
        'monthly_totals',
        existing_comment='当月产量',
        schema=None
    )
    op.alter_column('qa', 'line',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('qa', 'day',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=5),
               existing_nullable=True)
    op.alter_column('qa', 'month',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=10),
               existing_nullable=True)
    op.alter_column('qa', 'year',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=10),
               nullable=True)
    op.alter_column('qa', 'value',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
    op.create_index(op.f('ix_qa_line'), 'qa', ['line'], unique=False)
    op.drop_column('qad', 'scrap_rate_m')
    op.drop_column('qad', 'scrap_rate_c')
    op.alter_column('routes', 'path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('routes', 'name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
    op.alter_column('routes', 'sort_order',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_index('ix_routes_name', table_name='routes')
    op.drop_constraint('routes_ibfk_1', 'routes', type_='foreignkey')
    op.create_foreign_key(None, 'routes', 'routes', ['parent_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', mysql.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'routes', type_='foreignkey')
    op.create_foreign_key('routes_ibfk_1', 'routes', 'routes', ['parent_id'], ['id'])
    op.create_index('ix_routes_name', 'routes', ['name'], unique=True)
    op.alter_column('routes', 'sort_order',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('routes', 'name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.alter_column('routes', 'path',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.add_column('qad', sa.Column('scrap_rate_c', mysql.FLOAT(), nullable=True))
    op.add_column('qad', sa.Column('scrap_rate_m', mysql.FLOAT(), nullable=True))
    op.drop_index(op.f('ix_qa_line'), table_name='qa')
    op.alter_column('qa', 'value',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('qa', 'year',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('qa', 'month',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('qa', 'day',
               existing_type=sa.String(length=5),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('qa', 'line',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.create_table_comment(
        'monthly_totals',
        '当月产量',
        existing_comment=None,
        schema=None
    )
    op.alter_column('departments', 'description',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=500),
               nullable=False)
    op.create_table('announcements',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('content', mysql.VARCHAR(length=1000), nullable=True),
    sa.Column('created_at', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('degree', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('type', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('important', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('visible_to', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', mysql.VARCHAR(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='announcements_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_announcements_id', 'announcements', ['id'], unique=False)
    op.drop_table('role_permission')
    op.drop_index(op.f('ix_route_permissions_id'), table_name='route_permissions')
    op.drop_table('route_permissions')
    # ### end Alembic commands ###
