"""empty message

Revision ID: b900a967c84e
Revises: d861bdbd577f
Create Date: 2025-02-24 14:01:48.296932

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b900a967c84e'
down_revision: Union[str, None] = 'd861bdbd577f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'end_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'end_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
