"""empty message

Revision ID: d861bdbd577f
Revises: 8c7195fd55d7
Create Date: 2025-02-24 10:50:33.296179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd861bdbd577f'
down_revision: Union[str, None] = '8c7195fd55d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qa', 'scrapflag',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('qa', 'scrapflag',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
