"""Add User model

Revision ID: de4d191c1743
Revises: 75ecbec9a6db
Create Date: 2025-02-18 14:30:00.345424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'de4d191c1743'
down_revision: Union[str, None] = '75ecbec9a6db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(length=50), nullable=True))
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'department_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'department_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
